### ISSUE TITLE
Question: Is it possible to use this with a local spark cluster, for local development and CI?

### ISSUE THREAD

**Issue by unj1m** [databricks/databricks-sql-python#106]
I'd like to be able to develop and run tests without having to connect to databricks.

**Comment by unj1m** [comment]
My use case is that as a developer, I prefer to develop locally and run tests without having to talk to a network service.

"No" is a valid/fair answer, and the answer I expected, but I thought I'd ask. :smile: .

I don't know as much as I probably about details of connecting to spark clusters, so I wasn't sure if this was basically just connecting to a spark cluster.

I'm not asking for a change, really just asking a question. If the answer is "no", please just close this ticket, or answer "no" and I will.

**Comment by susodapop** [comment]
I see. Thanks for clarifying. No, this connector isn't designed to work with a local spark cluster.

**Comment by nchammas** [comment]
> My use case is that as a developer, I prefer to develop locally and run tests without having to talk to a network service.

Just want to echo this sentiment for the record. It's unfortunate that both this project and [databricks-connect][1] don't make any affordances for [local testing against open source Spark][2].

[1]: https://pypi.org/project/databricks-connect/
[2]: https://community.databricks.com/t5/data-engineering/installing-databricks-connect-breaks-pyspark-local-cluster-mode/m-p/105527
