### ISSUE TITLE
SSL errors when pysql used across many threads

### ISSUE THREAD

**Issue by susodapop** [databricks/databricks-sql-python#111]
Databricks employee here 👋 We've had a few support cases in the last couple months where pysql falls with unpredictable SSL errors when many connections are opened across multiple threads (this is easily reproduced using dbt with a 10k model project running 20+ threads). The most common error message we see is `Error during request to server: EOF occurred in violation of protocol (_ssl.c:992)`.

But we've also seen unusual 200 http response codes that nevertheless have an error "Connection Refused"

We've also seen `[Errno 8] nodename nor servname provided, or not known `

The fix for this is likely to implement HTTPS connection reuse by the driver. As we are a `thrift`-based client and `thrift` is unsophisticated, the driver makes many roundtrips for each RPC. We're inclined to implement this by subclassing Thrift's HTTPTransport and hooking in `requests` which performs connection pooling and reuse "for free".

**Comment by alexwainger** [comment]
Just a +1 on this, I'm sporadically getting the "EOF occurred in violation of protocol" error when using the DatabricksSqlHook across a number of concurrent tasks in Airflow. Would be a huge help to get it fixed!

**Comment by susodapop** [comment]
Hey @alexwainger are you still observing issues with this on the latest version of databricks-sql-connector? We've implemented HTTPS connection reuse as of 2.6.0 and I can no longer reproduce the same issues in my test bed.
