### ISSUE TITLE
SQLAlchemy dialect `has_table` doesn't use the schema name.

### ISSUE THREAD

**Issue by unj1m** [databricks/databricks-sql-python#115]
[has_table](https://github.com/databricks/databricks-sql-python/blob/398ab445efc7ad73c4c666817a0e584547e5b2fb/src/databricks/sqlalchemy/dialect/__init__.py#L275-L293) gets the schema namebut [doesn't pass it](https://github.com/databricks/databricks-sql-python/blob/398ab445efc7ad73c4c666817a0e584547e5b2fb/src/databricks/sqlalchemy/dialect/__init__.py#L285) to `DESCRIBE`.

This causes SQLAlchemy to fail to drop a given table (in a given schema).

**Comment by narquette** [comment]
Agree. Having the same experience. This is a simple fix. I've changed it locally and it works without issue.

**Comment by narquette** [comment]
@susodapop Can we get someone assigned to this ticket?
