### ISSUE TITLE
Delta has TINYINT now which needs to be added in?

### ISSUE THREAD

**Issue by Data-drone** [databricks/databricks-sql-python#123]
I got:

```
CompileError: (in table 'dimaccount', column 'taxstatus'): Compiler  can't render element of type TINYINT
```
When working with a sqlalchemy engine with the databricks dialect enabled connected to a SQL Warehouse endpoint.

See:  https://docs.databricks.com/sql/language-manual/sql-ref-datatypes.html#supported-data-types

**Comment by susodapop** [comment]
Thanks for reporting. Fix incoming.
