### ISSUE TITLE
sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [TABLE_OR_VIEW_ALREADY_EXISTS] 

### ISSUE THREAD

**Issue by coreystokes-8451** [databricks/databricks-sql-python#133]
Hello, 

I am using alembic with the sql connector and I just started getting the above error. It seems alembic is applying the migration in databricks before actually reading the migration script

I am using connector 2.5.2 and alembic 1.10.4 (i also tried 1.11.1)

**Comment by susodapop** [comment]
This does not reproduce for me. Can you provide reproduction steps?

**Comment by coreystokes-8451** [comment]
we actually resolved this. Thanks!

**Comment by susodapop** [comment]
For future searchers do you have any insight about the cause?
