### ISSUE TITLE
Primary Key constraint SQLAlchemy

### ISSUE THREAD

**Issue by pichlerpa** [databricks/databricks-sql-python#149]
Hello,

Do you know if I can access the Primary Key constraint information (with Unity Catalog) using SQLAlchemy and this connector?
I tried the following two ways using the Runtime Inspection API, but in both cases the result is empty:

```
inspector = sa.inspect(conn)

inspector.get_columns(db_table, db_schema)
inspector.get_pk_constraint(db_table, db_schema)
```

Thanks,
Patrick

**Comment by susodapop** [comment]
I can confirm that this doesn't work at all right now because we haven't wired-in this behaviour with the sqlalchemy dialect yet. We'll get to it eventually, but are also open to a pull request implementing this behaviour.

**Comment by pichlerpa** [comment]
Hi @susodapop,

thanks for your response, good to know, then I need to be patient I guess :)

Patrick
