### ISSUE TITLE
Support saved query in SQL datawarehouse ?

### ISSUE THREAD

**Issue by pdscodes** [databricks/databricks-sql-python#16]
similar to a stored procedure in sql server,

there may be many statements in one saved query (with parameters) in SQL data warehouse.

is this type of call supported?

**Comment by susodapop** [comment]
Spark SQL doesn't support saved queries / stored procedures. Therefore it's impossible with our connector.

The connector can _run_ multi-statement queries; but only if you pass it the complete text of the query + any parameters. Spark SQL has no way to save these by name.

**Comment by mroy-seedbox** [comment]
Instead, these procedures could be stored as functions in whatever tool you use to make the calls.

In DBT for example, you could use macros (with parameters) or custom materializations (with variables).

**Comment by susodapop** [comment]
Exactly @mroy-seedbox. With Databricks workflows you can use sql task as workflow objects too, which is a similar idea.

**Comment by pdscodes** [comment]
> Instead, these procedures could be stored as functions in whatever tool you use to make the calls.
> 
> In DBT for example, you could use macros (with parameters) or custom materializations (with variables).

great, I tested the function and it works

cursor.execute("SELECT * FROM db.fn_dnl_act_pay_dt(%(parm1)s, %(parm2)s, %(parm3)s);", {"parm1": "abc", "parm2": "bcd", "parm3": "fgh"})

only issue is I need must add database name before the table name, or it will fail.
Exception has occurred: ServerOperationError
Table or view not found: 

use view does not require add database name before table name

**Comment by pdscodes** [comment]
> Exactly @mroy-seedbox. With Databricks workflows you can use sql task as workflow objects too, which is a similar idea.

you mean dbt task? SQL task is not available from drop down

![image](https://user-images.githubusercontent.com/19292708/178890739-e1459c90-846d-49f1-b836-10e5d5bb36f0.png)
