### ISSUE TITLE
Unable to access Databricks warehouse due to lost session after a few hours of service uptime

### ISSUE THREAD

**Issue by daniDubinsky** [databricks/databricks-sql-python#162]
Hi,
I am using databricks-sql as part of a REST microservice that is supposed to access the data using Databricks warehouse. After some time that the service is up (more than a few hours), I noticed that I can't access the data warehouse using the established connection because the session is lost. I create one session when the pod starts and that's it.
i manage to resolve this if i redeploy the pod, so it establishes a new connection.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/app/dapi/middleware.py", line 52, in decorated
    return await func(*args, **kwargs)
  File "/app/dapi/online.py", line 32, in get_openweb_online_query
    result = await dabi_dbx_warehouse.query_databricks_sql(query)
  File "/app/dapi_handlers/dbx_wh_handler.py", line 63, in query_databricks_sql
    cursor.execute(query)
  File "/usr/local/lib/python3.8/site-packages/databricks/sql/client.py", line 472, in execute
    execute_response = self.thrift_backend.execute_command(
  File "/usr/local/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 832, in execute_command
    resp = self.make_request(self._client.ExecuteStatement, req)
  File "/usr/local/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 393, in make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/usr/local/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 261, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server: BAD_REQUEST: Invalid SessionHandle: Session [01ee149b-17c0-1444-95f6-c1d380554387] is closed.
```

this is how i query the warehouse:
```python
with self.dbx_connection.cursor() as cursor:
    cursor.execute(query)
    return cursor.fetchall_arrow()
```

when self.dbx_connection is initialized in that start of the service once

### Steps to Reproduce:

1. Start the microservice.
2. Wait for a few hours.
3. Attempt to access the Databricks warehouse using the established connection.
4. Encounter the "Invalid SessionHandle" error.

### Expected Behavior:
The session should remain active and allow continued access to the Databricks warehouse even after a few hours of service uptime.

### Actual Behavior:
After a few hours, the session is closed, resulting in the "Invalid SessionHandle" error when trying to access the Databricks warehouse.

**Comment by susodapop** [comment]
At present this is expected behaviour for `databricks-sql-connector`. Sessions on Databricks are not like sessions on a traditional database: they consume memory, prevent the compute resource from terminating and therefore incur cloud closts. They aren't intended to sit idle for hours at a time. 

Thankfully, creating new sessions is fast. So to workaround this, you should implement an idle connection timeout at your application level. If the application hasn't used its session in awhile it will automatically recycle it and create a new session the next time your app asks for one. Sqlalchemy provides these. From a passing search it appears asgiref may have one as well.

**Comment by daniDubinsky** [comment]
> At present this is expected behaviour for `databricks-sql-connector`. Sessions on Databricks are not like sessions on a traditional database: they consume memory, prevent the compute resource from terminating and therefore incur cloud costs. They aren't intended to sit idle for hours at a time.
> 
> Thankfully, creating new sessions is fast. So to workaround this, you should implement an idle connection timeout at your application level. If the application hasn't used its session in awhile it will automatically recycle it and create a new session the next time your app asks for one. Sqlalchemy provides these automatically with its connection pools. From a passing search it appears asgiref may have one as well.

Thank you @susodapop, i fixed my service to reestablish the connection every time i query, TBH it takes around 1 Second to reconnect, which It's not something marginal.
There is a chance in the future to have a logic that keeps connected?

**Comment by susodapop** [comment]
@daniDubinsky The goal isn't to reconnect every time you query. That is of course slow and not optimal. You should instead implement an _**idle**_ connection timeout, which only recreates a session if your application hasn't used its connection for a long time (this could be anywhere from 1-4 hours). Using this approach will sometimes incur the 1-second connection penalty. But certainly not on every query (unless you only query Databricks every few hours).

**Comment by susodapop** [comment]
> There is a chance in the future to have a logic that keeps connected?

We may implement this in the future but it is not currently on the roadmap.

**Comment by daniDubinsky** [comment]
ok thank you very much

**Comment by sebbegg** [comment]
@susodapop Sorry for reviving this topic:
We face the same issue even though we're using a sqlalchemy pool with `pool_recycle=3600` (i.e. 1 hour).
Is there any documentation from databricks what the "idle timeout" of a session on server side is?
