### ISSUE TITLE
SQLAlchemy dialect ignores if_exists parameter

### ISSUE THREAD

**Issue by james-miles-ccy** [databricks/databricks-sql-python#165]
The parameter 'if_exists' is being ignored when using pandas dataframe and to_sql() for appending or replacing existing tables in Databricks via sqlalcemy dialect.

I am currently running the below:

df.to_sql(table_name
,engine
,schema=schema
,index=False
,method="multi"
,if_exists="append")

getting error:

[TABLE_OR_VIEW_ALREADY_EXISTS] Cannot create table or view  because it already exists.

**Comment by susodapop** [comment]
What version of pandas are you using?

**Comment by james-miles-ccy** [comment]
I have tried both 2.0.3 and 1.4.4 to no avail

**Comment by susodapop** [comment]
I'm not able to reproduce with the following versions:

```
databricks-sql-connector==2.7.0
pandas==1.3.5
SQLAlchemy==1.4.48
```

To test this I ran our e2e test for pandas uploads **twice** and removed the `finally` clause:

```python
def test_pandas_upload(db_engine, metadata_obj):

    import pandas as pd

    SCHEMA = os.environ.get("schema")
    try:
        df = pd.read_excel("tests/sqlalchemy/demo_data/MOCK_DATA.xlsx")
        df.to_sql(
            "mock_data",
            db_engine,
            schema=SCHEMA,
            index=False,
            method="multi",
            if_exists="append",
        )

        df_after = pd.read_sql_table("mock_data", db_engine, schema=SCHEMA)
        assert len(df) == len(df_after)
    except Exception as e:
        raise e
    finally:
        #db_engine.execute("DROP TABLE mock_data")
        import logging
        logger = logging.getLogger("databricks.sql")
        logger.info("Not removing existing table")
```

**Comment by james-miles-ccy** [comment]
would you mind trying the latest versions of pandas and sqlalchemy?

**Comment by susodapop** [comment]
databricks-sql-connector is pinned to pandas versions below 2.0

But I ran with: `pandas==1.4.4` and the append behaviour still works. So the issue may be the version of SQLAlchemy instead.

What version of SQLAlchemy are you using?

**Comment by james-miles-ccy** [comment]
2.0.17 which I believe is the latest version

**Comment by susodapop** [comment]
Well that's the issue. databricks-sql-connector doesn't support SQLAlchemy==2.0.0 or above (yet). 

https://github.com/databricks/databricks-sql-python/issues/91

**Comment by james-miles-ccy** [comment]
I also tried SQLAlchemy 1.4 and produces the same error, very strange indeeed

**Comment by susodapop** [comment]
hmm, i’d like to get you unblocked. Can you please contact Databricks
support about this? i’d like to know more about your environment. I suspect
this may be an issue with the way that the SQL gateway returns status
messages

**Comment by susodapop** [comment]
Updating this issue to say that we may have isolated the issue to whether or not the SQLAlchemy connection string includes a `catalog` declaration.

### Doesn't work
```python
engine = create_engine(
    f"databricks://token:{token}@{host}?http_path={path}&schema={schema}",
)
```

### Works
```python
engine = create_engine(
    f"databricks://token:{token}@{host}?http_path={path}&schema={schema}&catalog={catalog}",
)
```

**Comment by james-miles-ccy** [comment]
This has fixed the issue! you need to make sure that both the catalog and schema is present within the connection string for if_exists to function correctly. Thankyou for your assistance
