### ISSUE TITLE
"Failed to establish a new connection", when connecting to SQL Warehouse

### ISSUE THREAD

**Issue by JulesHuisman** [databricks/databricks-sql-python#166]
When trying to connect to a SQL warehouse from a Databricks notebook in a workspace with Unity enabled we get the following error. We are using the package in `dbt-databricks`

```
HTTPSConnectionPool(host='adb-6473457167070464.4.azuredatabricks.net', port=443): Max retries exceeded with url: /sql/1.0/warehouses/0866f61ebc49d20f (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))
```

It used to work before we enabled Unity in the workspace, so I might have something to do with that.

Debugging we tried:
1. Connected from a local machine to the SQL Warehouse -> This works.
2. Connected from the Unity workspace a SQL Warehouse in a non-Unity workspace -> This works.
3. Tried multiple older versions of the package -> Didn't work.

**Comment by susodapop** [comment]
Hi @JulesHuisman can you contact Databricks support for this? I don't believe this is an issue with the connector. It would be best not to post your connection details (domain + sql ware house http path) on a public forum.

**Comment by JulesHuisman** [comment]
> Hi @JulesHuisman can you contact Databricks support for this? I don't believe this is an issue with the connector. It would be best not to post your connection details (domain + sql ware house http path) on a public forum.

Will do, and I removed the details.
