### ISSUE TITLE
Add urllib3 as an explicit dependency

### ISSUE THREAD

**Issue by jacobus-herman** [databricks/databricks-sql-python#190]
Hi!

Can you please add `urllib3` as an explicit dependency to your package? I see that in the latest version, i.e. `2.9.0`, you are using `BaseHTTPResponse` from `urllib3` and this is only available in `urllib3>=2.0.0`. So can you either add this dependency or change the code to accommodate older versions of `urllib3`? :)

**Comment by susodapop** [comment]
Thanks for opening this issue! Excellent catch.

**Comment by dthemg** [comment]
An issue with this is that `botocore` requires `urllib3` version 1, you can't have both installed:
```
botocore 1.31.29 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.4 which is incompatible
```

**Comment by susodapop** [comment]
A fix for this has merged to main and will release today as part of 2.9.2

**Comment by susodapop** [comment]
Release 2.9.2 is now live on Pypi
