### ISSUE TITLE
User Agent string is getting mangled

### ISSUE THREAD

**Issue by nhorton** [databricks/databricks-sql-python#192]
We are passing in a string for our user agent (Unsupervied) to the connector via the DSN and using SQLAlchemy to access Databricks. "sqlalchemy + " is getting added over and over. The screenshot has 5 examples of it being added, but it is variable - we see some with hundreds.

I think this matters to Databricks as an org more than end-developers as this is breaking your analytics about tools using Databricks.

![image](https://github.com/databricks/databricks-sql-python/assets/204146/5a49168c-b00a-46f2-acb0-03acc8fa50af)

**Comment by nhorton** [comment]
We figured out what is happening. 
https://github.com/databricks/databricks-sql-python/blob/0d99fc738d45042ef19ee753723d12b4833e8812/src/databricks/sqlalchemy/dialect/__init__.py#L330


You are updating the dict *that we pass in as arguments* with your altered user agent string. That means that if one instantiates multiple SQLAlchemy engines, then these build up over time.

If you can't just keep your altered version of the string without writing it to the dict, you could clone the dict passed in and not alter the original, that would work. We are doing a workaround where we clone it ourselves before passing to you, but this should likely be fixed in the dialect itself.

**Comment by susodapop** [comment]
Thanks for the report and the RCA. Yes, we'll fix this in the dialect.
