### ISSUE TITLE
Upgrade from 2.8.0 to 2.9.0 introduces ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3'

### ISSUE THREAD

**Issue by mrpowerus** [databricks/databricks-sql-python#194]
Upgrading to the new version of the databricks package introduces the following error:

ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3'

Environment: DBR 12.2LTS (Unity Catalog Enabled)

**Comment by leo-schick** [comment]
Yes, this is fixed by #190 which had not been released yet. See my issue #193

**Comment by potiuk** [comment]
Same for Apache Airflow

**Comment by potiuk** [comment]
Assume it will be fixed in the next version of connector and we can just exclude 2.9.0. I guess you will also yank it ?

**Comment by VOVELEE** [comment]
same issue here in 10.4 LTS

**Comment by potiuk** [comment]
Yep. I'd also suggest yanking. This kind of errors is really a "please don't install me at all" case - and also yanking has a very little surface (if at all) to cause any problems. Yanking is as soft as possible when it comes to marking release as problematic and has no side-effects really, other than it will be skipped by automated resolution by `pip` and others and that it will print a warning when forcefully installed by specifying `==`.

**Comment by mrpowerus** [comment]
I agree, please yank it.

**Comment by susodapop** [comment]
This is resolved in https://github.com/databricks/databricks-sql-python/pull/197 and released as version 2.9.2.
