### ISSUE TITLE
Connections `executemany` implementation is not a prepared statement. 

### ISSUE THREAD

**Issue by martinitus** [databricks/databricks-sql-python#196]
While [PEP249](https://peps.python.org/pep-0249/#executemany) says

> Modules are free to implement this method using multiple calls to the [.execute()](https://peps.python.org/pep-0249/#id21) method or by using array operations to have the database process the sequence as a whole in one call.

Just reading the docstring from the connection class is maximally misleading:

https://github.com/databricks/databricks-sql-python/blob/7aaa014172cb1c1e32a7776f81f6b75d66d4717a/src/databricks/sql/client.py#L527-L538

As a user, I (of course) assumed that databricks-sql-connector does something smart like e.g. batched inserts for a insert query. Instead I find that I have many thousand sequentially executed individual insert requests, one for each row.

I suggest to change the docstring to point out that behaviour!

**Comment by susodapop** [comment]
This is a good callout. We don't have plans to implement prepared statements for this connector (although I've created a ticket internally so we can monitor the demand for this feature). Meanwhile, updating the docstring like you did in your pull request is a sensible change.

**Comment by martinitus** [comment]
Ping. Want to merge this?

**Comment by susodapop** [comment]
Thanks for the ping. Will get this landed shortly.
