### ISSUE TITLE
how to store SQL query result data to local disk?

### ISSUE THREAD

**Issue by bachhavdipak** [databricks/databricks-sql-python#20]
I am a newbie to data bricks and trying to write results into the excel/ CSV file using the below command but getting DataFrame' object has no attribute 'to_csv' errors while executing.

I am using a notebook to execute my SQL queries and now want to store results in the CSV or excel file

%python

`df =spark.sql ("""select * from customer""") `
and now I want to store the query results in the excel/csv file. I have tried the below code but it's not working

`df.coalesce(1).write.option("header","true").option("sep",",").mode("overwrite").csv("file:///C:/New folder/mycsv.csv")   `   
AND

`df.write.option("header", "true").csv("file:///C:/New folder/mycsv.csv")`

**Comment by susodapop** [comment]
Hi there, this repository is for the Python connector to Databricks SQL. Your question is about executing commands in notebooks which is beyond our scope. You can direct these support questions to https://community.databricks.com/s/ or through official Databricks support: https://support.databricks.com/s/

Good luck!
