### ISSUE TITLE
Can not use the urllib3 v1: ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3' 

### ISSUE THREAD

**Issue by trancongtuanmanh** [databricks/databricks-sql-python#203]
Upgrading to the new version of the databricks package introduces the following error:

ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3'

Environment: 
- DBR 12.2LTS 
- dbt-databricks==1.4.2
- python3.9

**Comment by trancongtuanmanh** [comment]
I have a way to work around, try to install urllib3>=2.0.0, but this is not a right way to solve this problem.

**Comment by susodapop** [comment]
This was closed already by https://github.com/databricks/databricks-sql-python/pull/197. Install databricks-sql-connector==2.9.2

**Comment by trancongtuanmanh** [comment]
> This was closed already by #197. Install databricks-sql-connector==2.9.2

Thank you ! It is ok at 1.26.9 version
