### ISSUE TITLE
Unable to Import DatabricksSesssion (pyspark import issue)

### ISSUE THREAD

**Issue by narquette** [databricks/databricks-sql-python#210]
**Issue:**

When I try to import the DatabricksSession class to instantiate spark, I get an pyspark import error?  I've tried to use different version of databricks-sql-connector as well as pyspark but continue to get the same issue.

**Environment Information:**

- OS Windows
- Python == 3.10

**Python Libraries**

- pyspark==3.4.1
- databricks-sql-connector==2.9.2

Recreation Steps:

1. Try to import a databricks session class

```python
from databricks.connect import DatabricksSession
```

Expectation: I'm able to import the aforementioned class
Actual: I'm not able to import and get the following error:

```text
from pyspark.sql.connect.conversion import storage_level_to_proto, proto_to_storage_level
ImportError: cannot import name 'storage_level_to_proto' from 'pyspark.sql.connect.conversion'
```

**Comment by susodapop** [comment]
This issue is not relevant to this repository. You need to `pip install databricks-connect`, which is a different project. 

https://pypi.org/project/databricks-connect/
