### ISSUE TITLE
query length limitations

### ISSUE THREAD

**Issue by nofarm3** [databricks/databricks-sql-python#211]
Hi, I'm currently investigating the query length limitations for execution using this library. In the context of my usage, I'm dealing with dynamic queries of considerable length. I'm aiming to prevent any execution failures that might arise due to these lengthy queries. Could you clarify whether there's a specific character limit that serves as a clear constraint, or if the allowable query length is influenced by a variety of factors? Your insights would be greatly appreciated.

**Comment by susodapop** [comment]
This library enforces no constraint on the length of queries. There may exist such a limit in theory but we haven't seen it. From what you've written, I believe your use-case falls within the scope of this connector's capabilities.
