### ISSUE TITLE
Configurable timeout length 

### ISSUE THREAD

**Issue by C0DK** [databricks/databricks-sql-python#215]
I got a `databricks.sql.exc.ServerOperationError: DEADLINE_EXCEEDED: This operation took too long` after 23 seconds. I cannot tell if this is a timeout on the communication with the actual SQL warehouse, or the actual operation timing out.  (the first of which I can configure with `socket_timeout` presumably. I assume, however, it's the latter. Could this be supported to be configured? I assumed, [from the documentation](https://docs.databricks.com/en/sql/language-manual/parameters/statement_timeout.html) that the timeout would be 2 days, but this doesn't seem to be the case. 

## Details
python 3.10
databricks-sql-connector = "==2.3.0" (not sure if this could have been fixed since, as I see 2.9.3 is the newest version)

**Comment by susodapop** [comment]
> I cannot tell if this is a timeout on the communication with the actual SQL warehouse, or the actual operation timing out.

It's the latter. This error is coming from the SQL warehouse, not from databricks-sql-connector internals. Please speak with Databricks support about debugging it further. It's not something we can configure in this connector and does not appear to be a bug.
