### ISSUE TITLE
SQLAlchemy: Connect With Multiple Catalogs And Schema

### ISSUE THREAD

**Issue by arunksoman** [databricks/databricks-sql-python#226]
Consider there is data warehouse with more than 10 catalog and lots of schemas. If we are doing something like in the following example: https://github.com/databricks/databricks-sql-python/blob/main/examples/sqlalchemy.py that will become a tedious process. Can we connect directly to datawarehouse and query each and every catalog and schema with SQLAlchemy. Can you provide an example for that? If it is not possible is it possible to add that feature?

**Comment by susodapop** [comment]
> Can we connect directly to datawarehouse and query each and every catalog and schema with SQLAlchemy.

Yes.

If I understand you correctly, this is already supported. A catalog and schema are required to build the connection but you can query across catalogs and schemas (assuming you use unity catalog).

**Comment by arunksoman** [comment]
Atleast adding an example for a SQLAlchemy select query with multiple catalog and schema will be helpful.

**Comment by susodapop** [comment]
Can you share an example of the code you're trying to run that doesn't work?
