### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by susodapop** [databricks/databricks-sql-python#26]
PySQL depends on Numpy which only added support for Python 3.10 on 22 June 22 in version 1.23.0. But we’re pinned to 1.21.1 . De facto, we don’t support Py3.10.

**Comment by susodapop** [comment]
Great idea. Done [here](https://github.com/databricks/databricks-sql-python/pull/27). I'm testing Python 3.10 support this week so it shouldn't be long.

**Comment by dbaxa** [comment]
> PySQL depends on Numpy which only added support for Python 3.10 on 22 June 22 in version 1.23.0. But we’re pinned to 1.21.1 . De facto, we don’t support Py3.10.



afaik numpy added support for python 3.10 in 1.21.3 back in April of this year ->  https://numpy.org/devdocs/release/1.21.3-notes.html
> The Python versions supported in this release are 3.7-3.10. If you want to compile your own version using gcc-11, you will need to use gcc-11.2+ to avoid problems.

It seems like they had to fix a number of issues as they came up for 1.21.x though with regards to python 3.10 support (1.21.4 fixed a wheel issue for mac amd64, & 1.21.6 provides a 32 bit wheel for windows 3.10).

**Comment by alexott** [comment]
This issue is causing problems in Airflow: https://github.com/apache/airflow/pull/25697#issuecomment-1218126453
