### ISSUE TITLE
Is it possible to use oauth generated token instead of personal access token?

### ISSUE THREAD

**Issue by xguse** [databricks/databricks-sql-python#271]
I would like my app to not be dependent on a particular user still being at the company. My app gets data using `databricks-sql-python` and currently uses a personal access token (pat). created by my user. 

I have created a service principal and generated an oauth secret and this seems like a more robust way to authenticate my app to `databricks-sql-python`. But I can not figure out how to do it. I see that this lib has code that seems to be for using oauth, but the docs only explain pats. I know I should not simply code in a curl call manually. But I am not even sure that it would work since the `access_token` arg is only ever shown to be given pats.

Is there a way to do this? and if so Is there a way to use OAuth python libs to manage the fetching and refreshing of tokens? 

Alternatively: I do not see this library on the list of tools that use client unified authentication. But does it?

**Comment by FaresBadrCA** [comment]
This sounds similar to issue #255.
The way I got around it in my application by calling the function below every time the application needed to use a databricks connection:

```
from msal import ConfidentialClientApplication

app = ConfidentialClientApplication(
        client_id = CLIENT_ID,
        client_credential = CLIENT_SECRET,
        authority = AUTHORITY
)

from sqlalchemy import create_engine

def get_databricks_connection(engine):
    token_response = app.acquire_token_for_client(scope = SCOPES)
    url = f"databricks://token:{token_response['access_token']}@{DATABRICKS_HOST}:443?http_path={DATABRICKS_HTTP_PATH}"

    if (engine.url != url):
        engine.dispose()
        engine = create_engine(url)

    return engine
```
 
In this scenario, I am using MSAL to get the authentication tokens, and sqlalchemy to manage the databricks connection.

It would be nice if the databricks library supported token generation and refresh, but hopefully this snippet above helps.

**Comment by xguse** [comment]
Does msal work with AWS etc?

**Comment by FaresBadrCA** [comment]
> Does msal work with AWS etc?

Probably not. I used MSAL because my application connects to Azure databricks, and MSAL takes care of caching the temporary tokens. 

I looked into it briefly and it looks like AWS has their own authentication library: boto3
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html

I'm guessing you can do the same thing I did above with boto3, replacing `app.acquire_token_for_client` with `session.get_credentials`. I  haven't tried it myself though. It looks like boto3 also helps with caching credentials similar to MSAL.

**Comment by susodapop** [comment]
Yes, oauth is supported in the connector. We have example scripts for both [M2M](https://github.com/databricks/databricks-sql-python/blob/main/examples/m2m_oauth.py) and [U2M](https://github.com/databricks/databricks-sql-python/blob/main/examples/interactive_oauth.py) invocations.

Automatic token refreshing will work in this way.

As for unified client auth I will need to double-check this internally and will follow-up on this ticket once I know for certain.

**Comment by xguse** [comment]
> Yes, oauth is supported in the connector. We have example scripts for both [M2M](https://github.com/databricks/databricks-sql-python/blob/main/examples/m2m_oauth.py) and [U2M](https://github.com/databricks/databricks-sql-python/blob/main/examples/interactive_oauth.py) invocations.
> 
> Automatic token refreshing will work in this way.

This is exactly what I was looking for. Thank you. I will now need to try to get it work, thanks.

> 
> As for unified client auth I will need to double-check this internally and will follow-up on this ticket once I know for certain.

This bit is less immediately important to me if the above works. Of course not needing to install the sdk would be nice in principle, but I really dont care that much in practice.

**Comment by gdubya** [comment]
This is how we solved it (for anyone else searching in the future):

```python

def credential_provider():
    config = Config(
        host          = f"https://{os.environ.get("DATABRICKS_HOSTNAME")}",
        client_id     = os.environ.get("DATABRICKS_CLIENT_ID"),
        client_secret = os.environ.get("DATABRICKS_CLIENT_SECRET")
    )
    return oauth_service_principal(config)

server_hostname = os.environ.get("DATABRICKS_HOSTNAME")
http_path       = os.environ.get("DATABRICKS_HTTP_PATH")
catalog         = os.environ.get("DATABRICKS_CATALOG")
schema          = os.environ.get("DATABRICKS_SCHEMA")
access_token    = credential_provider().oauth_token().access_token

engine = create_engine(
    url = f"databricks://token:{access_token}@{server_hostname}?" +
        f"http_path={http_path}&catalog={catalog}&schema={schema}"
)
...
```
