### ISSUE TITLE
Client automatically starts terminated clusters without any indication it has done so

### ISSUE THREAD

**Issue by nchammas** [databricks/databricks-sql-python#283]
It seems that if you connect to a terminated cluster using this client and try to run something, it will take care of automatically starting the cluster for you. That's neat.

But I think there should be some indication -- an INFO message, perhaps -- that the cluster was terminated and is being started. It's a judgement call, but it seems inappropriate to modify infrastructure quietly.

**Comment by susodapop** [comment]
Autostarting the compute is a [feature of Databricks itself](https://docs.databricks.com/en/sql/admin/create-sql-warehouse.html#start-a-warehouse), not this connector.

When `databricks-sql-connector` runs a query, it doesn't know whether the target compute is terminated or not. And this information is not passed to the Python driver. If SQL gateway restarts a terminated compute instance, this is invisible to Python which means it's not something we can expose in the Python logs.
