### ISSUE TITLE
sqlalchemy.types has no attribute 'Uuid'

### ISSUE THREAD

**Issue by dfinchdb** [databricks/databricks-sql-python#291]
After release of databricks-sql-connector 3.0.0 receiving error sqlalchemy.types has no attribute 'Uuid' when using:

from langchain.sqldatabase import SQLDatabase
db = SQLDatabase.from_databricks()

Downgrading to version 2.9.3 resolves the error. Multiple reports of this issue. Additional report that downgrading sqlalchemy to version 2.0.12 resolved error.

**Comment by susodapop** [comment]
What version of SQLAlchemy do you have installled?

**Comment by Fallinggator** [comment]
Thank you for going the extra mile Jesse.
