### ISSUE TITLE
Slow package import times in debug

### ISSUE THREAD

**Issue by ofx53** [databricks/databricks-sql-python#292]
Hi,

Environment:
Python 3.12.0 (also tried 3.8, 3.10)
databricks-sql-connector==3.0.0
SQLAlchemy==2.0.23
IDE: Vscode

When trying to connect to Databricks with SQLalchemy, we noticed huge delays in debug mode when trying to connect to the endpoint, taking multiple minutes. Digging through the code, we found that the hanging happened when importing the databricks.sqlalchemy package.

`import databricks.sqlalchemy`

Digging further in the code to find where is the problem, we found it was the 
ttypes.py that contains ~111k lines that take a long time to parse in debug.

When trying to time it out with a simple script:
```
import time

if __name__ == "__main__":
    start_time = time.time()
    from databricks.sql.thrift_api.TCLIService.ttypes import TSparkArrowResultLink
    print("Time to load: from databricks.sql.thrift_api.TCLIService.ttypes import TSparkArrowResultLink", time.time() - start_time)
```

Run without debugging:
    Time to load: from databricks.sql.thrift_api.TCLIService.ttypes import TSparkArrowResultLink 0.02857661247253418
Run with debugging:
    Time to load: from databricks.sql.thrift_api.TCLIService.ttypes import TSparkArrowResultLink 203.38593983650208

Would there be a way to reduce loading time of the package in debug?

Thanks in advance!

**Comment by susodapop** [comment]
I think the culprit is somewhere else in your environment or code. I used your reproduction steps and I get sub-second results in VSCode debug mode. I develop this connector in VSCode as well and have never seen this such delays.

`ttypes.py` is integral to the connector's functioning so eliminating it is not an option.

**Comment by ofx53** [comment]
Hi!

Thank you for the quick answer. Upon further research, the issue lies with the docker image used.

Pulling the image in the dockerfile using `FROM python:3.12` does lead to the issue. The source of the issue was not found.

For now the team will use an Ubuntu image in development and a minimal python3.12 image for the production app.

Thanks!

**Comment by susodapop** [comment]
Thanks for following up with your findings!

**Comment by boorboor** [comment]
Hi
I'm experiencing same problem while importing [this](src/databricks/sql/thrift_api/TCLIService/ttypes.py) module using python version 3.12 (not in a container) tries with python 3.11 are fine.

This is happening only when I run my application tests suit. Need to do more analysis...  

<img width="1648" alt="image" src="https://github.com/databricks/databricks-sql-python/assets/31289910/d5a4e7a2-e742-461a-82e5-ae70b1d2dd15">

**Comment by susodapop** [comment]
After some experimentation I've found the root cause of this and written about it here https://github.com/databricks/databricks-sql-python/issues/369#issuecomment-2000352199

The only workaround I can think of at the moment is to run your tests without the `--cov` flag ☹️

**Comment by WimSchmitz** [comment]
Hi @susodapop, thanks for your investigation! Are there workarounds for the general case of running sql.connect() in debug mode, not for pytest purposes?

I tried running it in:
Python 3.12.2 (also tried 3.12.6)
databricks-sql-connector==3.4.0
SQLAlchemy==2.0.35

**Comment by susodapop** [comment]
Hey @WimSchmitz, this shouldn't be affecting you in debug mode. So it might be a different bug? Can you share the relevant output of your `pip freeze` command and also what CLI command you are running to commence your debug session and @ me here?

Due to the way pytest-cov works, if it's included in your `import` chain it can affect the behaviour on import even if you are running outside a test environment.

**Comment by WimSchmitz** [comment]
Hi!

I set up a minimal example to reproduce:

**Python Version:**
3.12.2

**Poetry Dependencies**
```
[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
databricks-sql-connector = "^3.4.0"
uvicorn = "^0.30.6"
python-dotenv = "^1.0.1"
```

**Pip Freeze ouptut:**
```
annotated-types==0.7.0
anyio==4.6.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
databricks-sql-connector==3.4.0
et-xmlfile==1.1.0
fastapi==0.115.0
h11==0.14.0
idna==3.10
lz4==4.3.3
numpy==1.26.4
oauthlib==3.2.2
openpyxl==3.1.5
pandas==2.2.3
pyarrow==16.1.0
pydantic==2.9.2
pydantic_core==2.23.4
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
requests==2.32.3
six==1.16.0
sniffio==1.3.1
starlette==0.38.6
thrift==0.20.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
uvicorn==0.30.6
```

**FastAPI Code:**
```
from fastapi import FastAPI
from databricks import sql
from dotenv import load_dotenv
import os

app = FastAPI()

@app.get("/query")
def execute_query():
    load_dotenv()
    
    with sql.connect(
            server_hostname=os.environ["DATABRICKS_HOST"],
            http_path=os.environ["DATABRICKS_HTTP_PATH"],
            access_token=os.environ["DATABRICKS_TOKEN"]
        ) as conn:
        return conn.cursor().execute("SELECT 1").fetchall()
```

**Results:**
1. Startup SQL Warehouse
2. Run uvicorn app.main:app
3. GET localhost:8000/query
Running plain  --> results after 1 second 
Running in debug mode --> stuck on importing in the long ttypes.

**Comment by WimSchmitz** [comment]
Hi @susodapop, checking in if you had the time to look into this :)  Do you think going to Python 3.11 would fix the issue?

**Comment by susodapop** [comment]
Sorry for my late response here! Been quite busy on other projects. I've been trying to reproduce your slow import times during debug and am unable to do so with Python 3.12. Does this reproduce if you try with Python 3.11 or Python 3.13? Have you tried dropping your poetry environment and rebuilding it?

```
poetry env remove --all
poetry install
```
