### ISSUE TITLE
Reduce log noise while managing Connection session

### ISSUE THREAD

**Issue by clenost** [databricks/databricks-sql-python#302]
Hello, thanks for the work you've done here !

I'm using this lib to run queries against databricks using DBT. While doing that it creates lots of logs related to session management (see below), which makes it not easy to read/debug. It seems related to logger statements `logger.info` [L242](https://github.com/databricks/databricks-sql-python/blob/62eb1d407ab03fc2c57a6626bec2173dbdd8bbb3/src/databricks/sql/client.py#L242) & [L355](https://github.com/databricks/databricks-sql-python/blob/62eb1d407ab03fc2c57a6626bec2173dbdd8bbb3/src/databricks/sql/client.py#L355) in [src/databricks/sql/client.py](https://github.com/databricks/databricks-sql-python/blob/62eb1d407ab03fc2c57a6626bec2173dbdd8bbb3/src/databricks/sql/client.py)

<details>
<summary>Logs</summary>

```
...
12:10:47  databricks-sql-connector adapter: Closing session 01ee9a79-d0a2-1670-bfb3-dfdfe4cb9208
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0d9-14f7-a643-e7d43bf4c85a
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0be-1fa9-8b0b-4c61e6bbab13
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0c2-106d-a003-b2b6e95afe0b
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0e2-1f5c-b406-9b796c9c3748
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0c1-1778-9c57-41d8ac72bc3a
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0e3-17e7-93bf-f552ccf11dd9
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0ec-1b19-85cc-a7c394215e9e
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0d9-14f7-a643-e7d43bf4c85a
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0f4-119f-823f-15547898104e
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0f6-1ef3-9f85-304a48e7e6ce
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0fa-19f9-aff4-dbf9e8c7cda3
12:10:48  databricks-sql-connector adapter: Successfully opened session 01ee9a79-d0fd-1ab9-a6bb-c06708a4da92
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0e2-1f5c-b406-9b796c9c3748
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0e3-17e7-93bf-f552ccf11dd9
12:10:48  databricks-sql-connector adapter: Closing session 01ee9a79-d0ec-1b19-85cc-a7c394215e9e
...
```
</details>

Some questions : 
1. Why are those statements in `info` mode ? (and should I submit a PR to update it to `debug` statements)
2. Any idea how can I deactivate this ? If I was using the client directly, I could deactivate the logger. But using the dbt cli, it becomes quite complex
```python
from databricks.sql.client import logger

logger.setLevel(logging.WARNING)
```
3. If you want to keep this level of log, would it be possible to use some kind of parameters to deactivate ? like an env variable ?

Thanks for your help !

**Comment by susodapop** [comment]
> Why are those statements in info mode ? 

We believe this is the correct level of detail for these log messages. 

> Any idea how can I deactivate this ? ... would it be possible to use some kind of parameters to deactivate ? like an env variable ?

Yes, it's already built-in to dbt-databricks to control the log-level of databricks-sql-connector. You can set the environment variable `DBT_DATABRICKS_CONNECTOR_LOG_LEVEL` to any valid python log level (DEBUG, INFO, WARNING, ...).

**Comment by clenost** [comment]
Oh, nice, thanks for your help !
