### ISSUE TITLE
Obtain query execution time or query ID

### ISSUE THREAD

**Issue by manucorujo** [databricks/databricks-sql-python#348]
I am using the Databricks SQL connector for Python to execute queries (`cursor.execute(query)`) and would like to obtain the execution time for each query. I have already explored the option of retrieving it using the "list queries" endpoint of the Databricks API, which returns a list of queries with their respective IDs and execution times.

However, I am facing difficulty in finding a way to obtain the query_id of the executed query through a cursor method or parameter. I have searched the documentation thoroughly, but haven't been able to find a solution. Could someone please suggest a way to obtain the query_id or execution time through a cursor method or any other parameter? If that is not possible, I would appreciate any other less straightforward solution.

**Comment by kravets-levko** [comment]
@manucorujo I'm not a developer of this library, but I think you can try something like this:

```python
from databricks import sql
from uuid import UUID

connection = sql.connect(...)

cursor = connection.cursor()

cursor.execute(...)

if cursor.active_op_handle is not None:
    query_id = UUID(bytes=cursor.active_op_handle.operationId.guid)
    print(query_id)
```

**Comment by manucorujo** [comment]
This worked fine. Thank you!
