### ISSUE TITLE
cursor.execute returing error 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by MrKushank** [databricks/databricks-sql-python#366]
Whereas cursor.columns is working which shows that the connection with Databricks account is correct.
![Databricks_Issues](https://github.com/databricks/databricks-sql-python/assets/162430119/9dd0d4d8-3432-4d50-9a3f-6e064c4de78d)

**Comment by MrKushank** [comment]
![image](https://github.com/databricks/databricks-sql-python/assets/162430119/9f5e2afb-00bd-46f5-8427-4a1869c2c4db)

**Comment by MrKushank** [comment]
Uploading log file.

[results.log](https://github.com/databricks/databricks-sql-python/files/14507295/results.log)

**Comment by MrKushank** [comment]
Output of cursor.columns - 

![image](https://github.com/databricks/databricks-sql-python/assets/162430119/c82ed40a-6fd5-45f5-abbf-1fe61815eb67)

**Comment by kravets-levko** [comment]
@MrKushank Thank you for reporting this issue. I'd like to ask you for few things - it will help us a lot with debugging:

- please share your script (minimal reproducible example)
- if possible - try the same query using [Nodejs connector](https://github.com/databricks/databricks-sql-nodejs) or [Go connector](https://github.com/databricks/databricks-sql-go), and check if you have the same error or not.

Thank you!

**Comment by MrKushank** [comment]
import os, logging
from databricks import sql
import pandas as pd

logging.getLogger("databricks.sql").setLevel(logging.DEBUG)
logging.basicConfig(filename = "results.log",
                    level    = logging.DEBUG)

host = os.getenv("DATABRICKS_HOST")
http = os.getenv("DATABRICKS_HTTP_PATH")
token = os.getenv("DATABRICKS_TOKEN")

with sql.connect(server_hostname=host,
                 http_path=http,
                 auth_type="databricks-oauth") as connection:
    with connection.cursor() as cursor:
        #cursor.columns(schema_name="platforms", table_name="iop_import_sessions")
        cursor.execute('SELECT * FROM samples.nyctaxi.trips LIMIT 2')
        result = cursor.fetchall()
        cursor.close()
        for row in result:
            print(row)

**Comment by MrKushank** [comment]
Meanwhile pyodbc worked - 

import pyodbc
import os

conn = pyodbc.connect(
  "Driver=Simba Spark ODBC Driver;" +
  f"Host={os.getenv('DATABRICKS_HOST')};" +
  "Port=443;" +
  f"HTTPPath={os.getenv('DATABRICKS_HTTP_PATH')};" +
  "SSL=1;" +
  "ThriftTransport=2;" +
  "AuthMech=3;" +
  "UID=token;" +
  f"PWD={os.getenv('DATABRICKS_TOKEN')}",
  autocommit = True
)

**Comment by kravets-levko** [comment]
Thank you! I need some time to investigate this. Will get back to you soon

**Comment by kravets-levko** [comment]
P.S. One more question: are you using AWS or Azure instance?

**Comment by MrKushank** [comment]
Microsoft Azure Databricks Instance.

**Comment by kravets-levko** [comment]
@MrKushank I tried a lot, but unfortunately wasn't able to reproduce this issue. Few things that may differ in my case:

- are you using sql warehouse or compute cluster?
- which DBR version is it running?
- are you trying to run _that exact_ SQL query from your example?
- are you trying to run the only SQL query which immediately fails, or there are other queries that succeed before the other one fails?

**Comment by MrKushank** [comment]
> @MrKushank I tried a lot, but unfortunately wasn't able to reproduce this issue. Few things that may differ in my case:
> 
> * are you using sql warehouse or compute cluster?  **compute cluster**
> * which DBR version is it running?  **11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)**
> * are you trying to run _that exact_ SQL query from your example? **yes and i have tried other queries as well and not working with cursor.execute. Although cursor.columns works.**
> * are you trying to run the only SQL query which immediately fails, or there are other queries that succeed before the other one fails? **every SQL query with cursor.execute fails. but cursor.columns works.**

**Comment by MrKushank** [comment]
> I recommend replacing your call to `cursor.columns` with a `SHOW COLUMNS FROM :table` query. The `cursor.columns` method has been flaky for awhile, but even when it works it's much slower than a `SHOW COLUMNS` query.

**cursor.columns is working. problem is with cursor.execute.**

**Comment by kravets-levko** [comment]
@MrKushank Okay, so - seems it's a buggy behavior of CloudFetch feature in older DBR versions. I managed to reproduce this error in other connectors as well. I'll report it to a corresponding team. Meanwhile, the only workaround I can suggest is to pass `use_cloud_fetch=False` option to `sql.connect()`. Please try it and let me know if it helped

**Comment by MrKushank** [comment]
Yes, this helped. Thanks a lot.
