### ISSUE TITLE
Consider changing the version specification for `thrift`

### ISSUE THREAD

**Issue by dbaxa** [databricks/databricks-sql-python#37]
Consider changing the version specification for `thrift` - instead of having it as

* `thrift>=0.13.0,<0.14.0`

consider having 

* `thrift>=0.13.0<1.0.0` 

This may or may not make sense as I am not entirely sure what kind of versioning apache thrift is using as it doesn't seem to follow `semver`.

**Comment by susodapop** [comment]
Is this causing any build issues for you? We're unlikely to change the version specification without a strong reason. The current spec was written automatically by poetry.

**Comment by dbaxa** [comment]
@susodapop it isn't causing issues at the present time, the concern is that if there is a security with `thrift`, updating it may take longer otherwise due to version pinning. However, as I am not sure what type of versioning apache thrift is using it is hard to make a recommendation on a version range to pin to ...

**Comment by susodapop** [comment]
We'll keep an eye on this. Thanks for calling it out.
