### ISSUE TITLE
`databricks.sql.connect` hangs in a long retrying loop when an invalid access token is used

### ISSUE THREAD

**Issue by mbelak-dtml** [databricks/databricks-sql-python#372]
## Steps to reproduce
Supply any invalid access token to `databricks.sql.connect`, e.g.
```python
sql.connect(
     server_hostname=my_workspace_url,
     http_path=http_path_to_my_warehouse,
     access_token="this-is-not-a-valid-access-token"
)
```

## Current behavior
The call gets stuck in a long retrying loop, eventually failing with a `RequestError`, which does not indicate an authentication error.

## Expected behavior
The function immediately raises an exception indicating an authentication error.

**Comment by mbelak-dtml** [comment]
Related
https://github.com/databricks/databricks-sql-python/issues/346#issuecomment-1967984742

**Comment by susodapop** [comment]
The fix for this has merged.
