### ISSUE TITLE
SQLAlchemy engine from workspace level service principle?

### ISSUE THREAD

**Issue by timharsch** [databricks/databricks-sql-python#376]
From a remote client, I need to write a script that connects to my SQL Warehouse using a workspace level service principal and creates an SQLAlchemy engine.. which I can then pass to a library that expects the engine.

I did write example scripts that:
* connect using the Service Principal via python dbapi, thanks to the example provided.
* creates a SQLALchemy engine using a PAT

I tried quite a few things including using pyodbc, only to discover that it fails as databricks_dbapi/odbc.py only supports username/password or PAT

Is there a way to create a SQLAlchemy engine connected to a SQL Warehouse using a service principle?

**Comment by susodapop** [comment]
Hey @timharsch what you're describing _should_ work without issue. Where are you finding this `odbc.py` file? The `databricks-sql-connector` is a native thrift client that doesn't depend on ODBC at all. Which makes me wonder if you're using the right connector.

**Comment by timharsch** [comment]
I guess the issue was failing to understand that service principals do not specify a username and password to connect.  The pattern that worked was to set the env vars like so:
    DATABRICKS_CLIENT_ID=...
    DATABRICKS_CLIENT_SECRET=..

and to use the pattern like so for the connect string:
    uri = f'databricks://{server_hostname}?http_path={http_path}&catalog={catalog}&schema={schema}'

to get the PyDB connection and feed it to the engine
