### ISSUE TITLE
loosen, update, or widen pyarrow dependencies

### ISSUE THREAD

**Issue by cburroughs** [databricks/databricks-sql-python#390]
databricks-sql-connector 3.1.2 has `Requires-Dist: pyarrow (>=14.0.1,<15.0.0)`

I know that's a "major version", but pyarrow releases "major versions" often, and as of this writing [16.1.0](https://pypi.org/project/pyarrow/16.1.0/) is the latest, with databricks-sql-connector being 2 major versions behind.  Since pyarrow is a very widely used dependency having this narrow dependency constraint can make resolution difficult to impossible.

**Comment by susodapop** [comment]
This seems like a sensible change. Have you considered opening a pull request implementing it? Presuming it passes the repository's automated e2e tests it would be a solid incremental improvement.

**Comment by susodapop** [comment]
Actually it looks like there is already a PR open to partially address this, https://github.com/databricks/databricks-sql-python/pull/389
