### ISSUE TITLE
Error during request to server: [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by steiner-takeda** [databricks/databricks-sql-python#53]
Getting this error when trying to use this library to connect to Databricks cluster:

Error during request to server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)

How can I disable SSL ? Similar to verify=False in requests library.

**Comment by susodapop** [comment]
You can disable SSL entirely by adding `_tls_no_verify=True` to your connection arguments when building a connection.

For example:


```python
from databricks import sql
import os

with sql.connect(server_hostname = os.getenv("DATABRICKS_SERVER_HOSTNAME"),
                 http_path       = os.getenv("DATABRICKS_HTTP_PATH"),
                 access_token    = os.getenv("DATABRICKS_TOKEN"),
                 _tls_no_verify=True) as connection:

...
```

**Comment by steiner-takeda** [comment]
thanks so much for such quick reply :) it worked but I came to another isssue: 
OperationalError: Error: expected server to use a protocol version >= SPARK_CLI_SERVICE_PROTOCOL_V2, instead got: 7
How can I setup correct protocol version?
Thanks!

**Comment by susodapop** [comment]
To what kind of cluster are you connecting? A SQL warehouse or an interactive cluster?

**Comment by steiner-takeda** [comment]
Not sure about answer, we are running both, databases and notebooks on this cluster

**Comment by alex-hsp** [comment]
Have the same issue with databricks sql commands ran by dbt-databricks.
Why this even an issue? Databricks cli work fine.

**Comment by fvanrossum** [comment]
If I look in thrift_backend.py and to the different [type of protocols](https://github.com/databricks/databricks-sql-python/blob/main/src/databricks/sql/thrift_api/TCLIService/ttypes.py) it seems like it references the following: "    HIVE_CLI_SERVICE_PROTOCOL_V8 = 7" . Maybe this connector currently doesn't account for connecting to Hive

**Comment by susodapop** [comment]
@fvanrossum I'll reiterate that this should be debugged privately with Databricks. I don't see any indication that this is a bug with the connector. Closing for now, but anyone is welcome to reopen the issue if they can demonstrate a bug in the connector code.
