### ISSUE TITLE
Access to Spark UI / Ganglia from connection

### ISSUE THREAD

**Issue by craustin** [databricks/databricks-sql-python#62]
It would be nice to be able to get a URL to the Spark UI / Ganglia metrics from the connection object. It would be useful to log these from running jobs for debugging performance issues.

```python
cluster_id = "XXXX-XXXXXX-testtest" # can we get this somehow?
driver_id = "12345678901234567890"  # and this?
spark_ui = f"https://adb-dp-{databricks_workspace}.6.azuredatabricks.net/sparkui/{cluster_id}/driver-{driver_id}/"
ganglia = f"https://adb-dp-{databricks_workspace}.6.azuredatabricks.net/driver-proxy/o/{databricks_workspace}/{cluster_id}/80/?c=cluster"
```

**Comment by susodapop** [comment]
This isn't something we'll ever expose through a DBSQL client. If needed the workspace admin has access to it through the ‘show Spark UI’ link in SQL history.
