### ISSUE TITLE
No COMMENT property when querying tables

### ISSUE THREAD

**Issue by mfcochauxlaberge** [databricks/databricks-sql-python#69]
When querying tables, I do not have the `COMMENT` property.

```python
tables = cursor.tables().fetchall()
```

I see `REMARKS`. It might not be exactly the same as `COMMENT`, but it's the closest thing I found so far. But the value I get seems to always be `'UNKNOWN'`.

Here is how I added a comment to a table:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/534861/203629747-916bc40e-6b39-4764-8683-e0dd8b5ccf33.png">

I want to know how to get the comment of a table using this Python client.

Using SQL isn't convenient because I need to call `DESCRIBE TABLE table` for each table and I am dealing with a very large number of tables.

Thank you for your help.

**Comment by cbornet** [comment]
You can get comments by querying the information_info schema
```sql
SELECT * FROM my_catalog.information_info.tables
```
I agree that it would be nice to also have it mapped to the REMARKS field in the thrift protocol  but that would have to be done on the server side.

**Comment by mfcochauxlaberge** [comment]
@cbornet Merci!

I'm no longer working on this, so I cannot easily test it. I'll take your word for it and close this. If it's still an issue for someone else they can open another issue.
