### ISSUE TITLE
SQLAlchemy dialect native bool support

### ISSUE THREAD

**Issue by ms32035** [databricks/databricks-sql-python#73]
Should be
```
class DatabricksDialect(default.DefaultDialect):
    """This dialect implements only those methods required to pass our e2e tests"""

    supports_native_boolean: bool = True
```
as otherwise bools are converted to ints which results in datatype errors

**Comment by susodapop** [comment]
Thanks for the tip. SQLAlchemy support hasn't merged into `main` yet so this won't be available generally. I'll apply this to our working branch.

**Comment by nicholasarquette** [comment]
Any idea when this branch will be merged into main?

**Comment by susodapop** [comment]
Answered here: https://github.com/databricks/databricks-sql-python/pull/57#issuecomment-1411162710
