### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

### ISSUE THREAD

**Issue by nicolai-at-ruhrdot** [databricks/databricks-sql-python#79]
When running the code at the bottom in a Conda environment I am having no problem connecting. However when switching to a pip virtualenv I am getting an SSL Certificate error. I need the code to run in a virtualenv in order to deploy AWS Lambda.

My guess is that pip deals with ssl certificates differently. Conda seems to have additional libraries for openssl and ca-certificates that Pip does not have. How can I resolve this issue? 

`File "/env/venv/lib/python3.7/site-packages/databricks/sql/thrift_backend.py", line 258, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)`

## Pip Environment
1. pipenv on python 3.7.2
2. Environment variables are correctly set.

Pip Packages:

certifi==2022.12.7
charset-normalizer==2.1.1
databricks==0.2
databricks-sql-connector==2.2.2
idna==3.4
lz4==4.3.2
numpy==1.21.1
oauthlib==3.2.2
pandas==1.3.5
pyarrow==10.0.1
python-dateutil==2.8.2
pytz==2022.7
requests==2.28.1
six==1.16.0
thrift==0.16.0
urllib3==1.26.13

Conda packages

## The code:
from databricks import sql
import os

with sql.connect(server_hostname = os.getenv("DATABRICKS_SERVER_HOSTNAME"),
                 http_path       = os.getenv("DATABRICKS_HTTP_PATH"),
                 access_token    = os.getenv("DATABRICKS_TOKEN")) as connection:

  with connection.cursor() as cursor:
    cursor.execute("SELECT * FROM default.diamonds LIMIT 2")
    result = cursor.fetchall()

Any tips would be greatly appreciated.

**Comment by susodapop** [comment]
It seems the exception is due to a self-signed certificate somewhere in the chain.

You can disable SSL entirely by adding `_tls_no_verify=True` to your connection arguments when building a connection.

For example:


```python
from databricks import sql
import os

with sql.connect(server_hostname = os.getenv("DATABRICKS_SERVER_HOSTNAME"),
                 http_path       = os.getenv("DATABRICKS_HTTP_PATH"),
                 access_token    = os.getenv("DATABRICKS_TOKEN"),
                 _tls_no_verify=True) as connection:

...
```

**Comment by nicolai-at-ruhrdot** [comment]
@susodapop Thank you! The problem turned out to be a local one (using Pipenv on macOS with an M2 chip). Certificates were not properly installed for my Python version, resulting in the virtual environment not being able to access them and receiving the SSL CERTIFICATE_VERIFY_FAILED error. 

I was able to solve this with the following command, if anyone on Mac is having the same problem:
`/Applications/Python\ 3.7/Install\ Certificates.command`

**Comment by susodapop** [comment]
Thanks for sharing your solution!
