### ISSUE TITLE
Library seems to ignore Schema/Database parameter

### ISSUE THREAD

**Issue by westernspion** [databricks/databricks-sql-python#83]
Setting the schema parameter does not have the desired effect. I have to set manually after the session is created.
This is a tad bit confusing since Databricks sort of merges the two terms (schema == database in the context of Databricks)

```
from databricks import sql
connection = sql.connect(server_hostname="myorg.cloud.databricks.com",
                                            http_path=/sql/protocolv1/o/<redacted>, 
                                            access_token=<redacted>, 
                                            schema="widget_schema")
cursor = connection.cursor()
cursor.execute('select current_database();')
print(cursor.fetchall())
## Prints "default" we would expect "widget_schema"

cursor.close()
connection.close()
```

I observed this behavior while trying to use the `sqlalchemy-databricks` package - it relies primarily on this package and on setting this parameter via the db url or a connect kwarg (neither work). Implementations such as Flask+SQLAlchemy do not give the ability to set the working schema in any other way. So I came here and was able to replicate the behavior purely with this package - which leads me to believe that the parameter is not working in this package. 

I also saw a stipulation that it requires DBR 9.0+ - I tried this on a 10.x cluster as well as a SQL warehouse - same behavior. 

I was able to reproduce strictly with this library

**Comment by westernspion** [comment]
Updating to 2.x solved this.

**Comment by susodapop** [comment]
FYI we are implementing our own SQLAlchemy dialect so you will not need `sqlalchemy-databricks` very soon.

**Comment by susodapop** [comment]
Since we aren't issuing further updates to versions < 2.x I'm closing this for now. Once our dialect for sqlalchemy is merged we'll open an issue on crflynn's repository inviting users to our first-party dialect.
