### ISSUE TITLE
Autoregistering extensions for Spark SQL?

### ISSUE THREAD

**Issue by giohappy** [databricks/databricks-sql-python#87]
Our use case is the registration of the [Apache Sedona](https://sedona.apache.org/latest-snapshot/) SQL extension to be able to execute geospatial queries:

```
--conf spark.sql.extensions=org.apache.sedona.viz.sql.SedonaVizExtensions,org.apache.sedona.sql.SedonaSqlExtensions \
--conf spark.kryo.registrator=org.apache.spark.serializer.KryoSerializer \
--conf spark.kryo.registrator=org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator
```

Is there any option to set these configurations with Databricks SQL Connector for Python?

**Comment by susodapop** [comment]
From what I understand, Databricks SQL doesn't support Spark Extensions so the Python connector can't enable them either. But you can use the Python connector with multi-purpose Databricks clusters, which do support Spark Extensions. In that case you would include these `conf` statements in the cluster init scripts.

If you need these features as part of DBSQL / SQL warehouses, you may be able to accomplish the same thing with [Python UDFs](https://docs.databricks.com/udf/python.html).

**Comment by giohappy** [comment]
@susodapop. Unfortunately it looks like configuring `SedonaSqlExtensions` is not enough. I also need to execute `SedonaRegistrator.registerAll(spark)`, which (I suppose) cannot be done inside an init script.

Thanks anyway for your reply.
